# Sample documents for semantic search demo — diverse topics for interesting matches.

documents = [
    "The mitochondria is often called the powerhouse of the cell because it generates most of the cell's supply of ATP through oxidative phosphorylation.",
    "Photosynthesis allows plants to convert sunlight, water, and carbon dioxide into glucose and oxygen in their chloroplasts.",
    "The theory of relativity, developed by Albert Einstein, revolutionized our understanding of space, time, and gravity.",
    "The Roman Empire reached its greatest territorial extent under Emperor Trajan in the early second century CE.",
    "The Industrial Revolution began in Britain in the late eighteenth century, transforming agriculture-based economies into manufacturing ones.",
    "Machine learning is a subset of artificial intelligence that enables systems to learn and improve from experience without explicit programming.",
    "Python is a high-level programming language known for its readable syntax and extensive standard library.",
    "Cloud computing delivers computing services such as servers, storage, and databases over the internet on a pay-as-you-go basis.",
    "The FIFA World Cup is the most widely viewed and followed sporting event in the world, held every four years.",
    "Basketball was invented by James Naismith in 1891 in Springfield, Massachusetts, as an indoor winter sport.",
    "Marathon running traces its origins to the legend of Pheidippides, who ran from Marathon to Athens to deliver news of victory.",
    "Sushi is a Japanese dish of prepared vinegared rice accompanied by seafood, vegetables, and occasionally tropical fruits.",
    "Italian cuisine is characterized by its simplicity, with many dishes having only four to eight ingredients.",
    "Dark chocolate contains flavonoids that may help improve blood flow and lower blood pressure when consumed in moderation.",
    "The human brain contains approximately 86 billion neurons connected by trillions of synapses.",
    "DNA carries the genetic instructions used in the growth, development, functioning, and reproduction of all known living organisms.",
    "Climate change refers to long-term shifts in temperatures and weather patterns, largely driven by human activities since the mid-1800s.",
    "The Amazon rainforest produces about 20% of the world's oxygen and is home to an estimated 10% of all species on Earth.",
    "Shakespeare wrote approximately 37 plays and 154 sonnets, and is widely regarded as the greatest writer in the English language.",
    "The printing press, invented by Johannes Gutenberg around 1440, made books affordable and spread literacy across Europe.",
    "Electric vehicles use one or more electric motors for propulsion, drawing power from rechargeable battery packs.",
    "Blockchain is a distributed ledger technology that records transactions across many computers in a way that makes tampering difficult.",
    "Jazz music originated in the African-American communities of New Orleans in the late nineteenth and early twentieth centuries.",
    "The Mona Lisa, painted by Leonardo da Vinci, is one of the most famous and valuable artworks in the world.",
    "Regular exercise improves cardiovascular health, strengthens muscles, and can reduce symptoms of anxiety and depression.",
    "Honey never spoils; archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.",
    "The Great Wall of China is a series of fortifications built over centuries to protect Chinese states from nomadic invasions.",
    "Quantum computing uses quantum bits or qubits that can exist in superposition, potentially solving certain problems far faster than classical computers.",
]
